services:
  - type: web
    name: twitter-scraper
    env: python
    buildCommand: bash render_build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CHROME_BIN
        value: /opt/render/project/.render/chrome/opt/google/chrome/google-chrome
